# Generated by Django 6.0.1 on 2026-04-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='meet_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
