# Generated by Django 5.2.3 on 2026-05-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lesson_meet_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_recorded',
            field=models.BooleanField(default=False),
        ),
    ]
