# Generated by Django 5.2.3 on 2026-05-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_is_recorded_to_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='audio_file_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
