# Generated by Django 6.0.1 on 2026-05-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_audio_file_path_to_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='ai_status',
            field=models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('completed', 'Завершено'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=20),
        ),
    ]
